@Api_HostAddress = http://localhost:5163
@User_Name = omarosos912@gmail.com
@User_Password = password!
# Login 
POST {{Api_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
    "identifier" : "{{User_Name}}",
    "password" : "{{User_Password}}"
}
